### PR TITLE
Update protobuf to 3.6.1.2

### PR DESCRIPTION
**Pull request by meteorcloudy**
Use one single protobuf external repo.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
FYI @jin

**Comment by jin** [comment]
@brettchabot not sure why import/copybara is failing, @brettchabot are there any logs for that?

**Comment by jin** [comment]
It looks like copybara isn't configured to export (and import?) changes made to the tools/ directory. 

I made an internal CL with the same change to test this out, and the tools/ directory changes were not exported out. https://github.com/android/android-test/pull/148

**Comment by jin** [comment]
I had to split this PR up internally, because it touches two packages that each have their own copybara export process. The changes are now in master; thanks @meteorcloudy for looking into this!!

**Pull request closed without merging**
