### PR TITLE
Bump Robolectric to 4.9

### PR DESCRIPTION
**Pull request by utzcoz**

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @brettchabot , looks like d8/r8 doesn't work correctly after updating Robolectric to 4.9. Do you have encountered similar problems?

**Comment by TWiStErRob** [comment]
I had a quick check (`gradlew :dependencies`) to get the tree with:
```gradle
repositories { mavenCentral() }
configurations { foo }
dependencies { foo("org.robolectric:robolectric:4.8.1") }
```

There are many transitive dependency changes in 4.9, **most notable might be guava** (apart from some minors and a new dependency).
image

Then I diffed the last master build and this PR's build and found that this `AnnotatedType` is missing:
image

I think that means that the new Robolectric versions bumps your Guava, which requires Java 8, but your minSdk is 14.

**Comment by utzcoz** [comment]
@TWiStErRob Thanks for your diagnostic. I will check whether I can  exclude this guava version from Robolectric  dependency.

**Comment by TWiStErRob** [comment]
Careful not to solve an xyproblem. As @brettchabot said it's unclear why is Robolectric used in build? Is it a dependency of Espresso, or is Espresso using Robolectric as a test dependency? (I genuinely don't know, I wouldn't expect an instrumentation library to depend on Robolectric. But then, it could be just some Bazel mishap.)

**Comment by utzcoz** [comment]
I used `bazel query "deps(//:axt_m2repository)"` to query dependencies of `axt_m2repository`, and I found that `axt_m2repository` doesn't have robolectric dependency, but it has `@maven//:v1/https/repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar` dependency brought by robolectric:

```
@maven//:com_google_gbazelisk build //:axt_m2repositoryuava_guava
@maven//:v1/https/repo1.maven.org/maven2/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
@maven//:org_checkerframework_checker_qual
@maven//:v1/https/repo1.maven.org/maven2/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar
@maven//:com_google_j2objc_j2objc_annotations
@maven//:v1/https/repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
@maven//:com_google_guava_failureaccess
@maven//:v1/https/repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
@io_bazel_rules_kotlin//third_party:android_sdk
@bazel_tools//tools/android:android_jar
```

**Comment by utzcoz** [comment]
android-test uses rules_jvm_external to load maven repositories(https://github.com/bazelbuild/rules_jvm_external/blob/master/private/rules/maven_install.bzl), and looks like it uses https://get-coursier.io/docs/other-version-handling as default algorithm to resolve dependency conflicts.

**Comment by utzcoz** [comment]
I run `bazel run @maven//:pin` to generate `maven_install.json` for axt, and I found this information in `maven_install.json`:

```
        "conflict_resolution": {
            "com.google.code.gson:gson:2.8.5": "com.google.code.gson:gson:2.8.6",
            "com.google.errorprone:error_prone_annotations:2.9.0": "com.google.errorprone:error_prone_annotations:2.11.0",
            "com.google.googlejavaformat:google-java-format:1.4": "com.google.googlejavaformat:google-java-format:1.5",
            "com.google.guava:guava:30.1.1-android": "com.google.guava:guava:31.1-jre",
            "com.google.guava:listenablefuture:1.0": "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava",
            "com.squareup:javapoet:1.9.0": "com.squareup:javapoet:1.13.0",
            "javax.annotation:javax.annotation-api:1.3.1": "javax.annotation:javax.annotation-api:1.3.2",
            "junit:junit:4.12": "junit:junit:4.13.2",
            "org.mockito:mockito-core:2.28.1": "org.mockito:mockito-core:2.28.2"
        },
```

**Comment by utzcoz** [comment]
I add a new commit to exclude guava from Robolectric dependency, and it works now. But I don't know why Robolectric's dependency can affect top level guava version. Hi @jin , do you have know the reason? Is that expected?

**Comment by utzcoz** [comment]
Hi @brettchabot could you help to take look at this PR again? Thanks.

**Comment by utzcoz** [comment]
Friendly ping @brettchabot for reviewing. Thanks.

**Pull request merged**
